### ISSUE TITLE
bad advice about the "battery limit"

### ISSUE THREAD

**Issue by ThomasWaldmann** [choeffer/gobuster#1]
In the README, you suggest to:
```
Kiosk Mode:  Battery Limit -> Enabled
```

I've looked up what this does and Microsoft documents that this tries to keep the battery charged at 50%, which is a good level for lithium batteries that are not really needed because the device is always connected to a power supply.

But for the general user, who likely uses this as a mobile device, it would reduce battery runtime to about half of what's possible.

So I suggest to either remove that advice or explain what it does and when it should be used.

**Comment by ThomasWaldmann** [comment]
I mean the line below "boot configuration".

A bit more down on the page, there is a link to the explanation from microsoft.

Still, I don't think it should be listed under "boot configuration" as "enabled", a lot of people might just set it and wonder...

**Comment by choeffer** [comment]
@ThomasWaldmann Thanks for the hint and taking the time to open the bug report. You are right and normal users would be confused if they do not know what this option does and just enable it. I added a link to the battery section where it is explained what this option does. So people can decide if they want to enable it or not. Do you think it is fine now?

**Comment by ThomasWaldmann** [comment]
Well, do you think most people run the device in kiosk mode (always connected to power supply) or why is the default "enabled"?

**Comment by ThomasWaldmann** [comment]
a widespread problem is that people don't read docs and just go with defaults, esp. if they do not understand what "kiosk mode" and "battery limit" means, assuming that this is ok for normal usage.

for those, adding one more link to the docs won't help. :-)

**Comment by choeffer** [comment]
> Well, do you think most people run the device in kiosk mode (always connected to power supply) or why is the default "enabled"?

It is recommended to change that setting because the Surface Dock is fully supported and people also might use the Surface Go connected to the dock when working at a desk.

> a widespread problem is that people don't read docs and just go with defaults, esp. if they do not understand what "kiosk mode" and "battery limit" means, assuming that this is ok for normal usage.
> 
> for those, adding one more link to the docs won't help. :-)

People who want to run Linux on a Surface device are not the average user I think, so the documentation level should be fine now :-)
